import type {
  GradeRegister,
  ThemeRegister,
  WeightRegister,
} from "../system/register.js";
import type { BiomeId } from "../next-experiments/biomes.js";

export type ShowcaseFamily =
  | "frontispiece"
  | "scene"
  | "material-study"
  | "field-guide"
  | "condition-atlas"
  | "stress-observatory"
  | "research-archive";

export type ShowcaseStatus = "published" | "utility" | "experimental";

export type ShowcaseManifest = {
  id: string;
  href: string;
  family: ShowcaseFamily;
  title: string;
  premise: string;
  focal: string;
  viewerRole: string;
  primaryRelation: string;
  temporalLaw: string;
  mobileMode: string;
  status: ShowcaseStatus;
  hostBiome?: BiomeId;
  grafts?: readonly string[];
  weight?: WeightRegister | null;
  theme?: ThemeRegister | null;
  grade?: GradeRegister | null;
};

const conditionRoutes: ShowcaseManifest[] = [
  {
    id: "drifting",
    href: "/drifting",
    family: "condition-atlas",
    title: "drifting",
    premise: "too many calls. let the channel cool.",
    focal: "rate limit",
    viewerRole: "waiting operator",
    primaryRelation: "release",
    temporalLaw: "cooldown",
    mobileMode: "recovery notice",
    status: "utility",
    grade: "cold-archive",
  },
  {
    id: "cooling",
    href: "/cooling",
    family: "condition-atlas",
    title: "cooling",
    premise: "the channel is full. let it rest.",
    focal: "overload state",
    viewerRole: "caretaker",
    primaryRelation: "hold",
    temporalLaw: "recovery interval",
    mobileMode: "status, then retry",
    status: "utility",
    grade: "cold-archive",
  },
  {
    id: "forbidden",
    href: "/forbidden",
    family: "condition-atlas",
    title: "forbidden",
    premise: "this route is closed. access is not cleared.",
    focal: "access boundary",
    viewerRole: "visitor at the threshold",
    primaryRelation: "interrupt",
    temporalLaw: "held threshold",
    mobileMode: "single threshold statement",
    status: "utility",
    grade: "interrogation",
  },
  {
    id: "gateway",
    href: "/gateway",
    family: "condition-atlas",
    title: "gateway",
    premise: "upstream has not answered.",
    focal: "missing upstream response",
    viewerRole: "relay operator",
    primaryRelation: "connect",
    temporalLaw: "waiting relay",
    mobileMode: "source, then recovery path",
    status: "utility",
    grade: "interrogation",
  },
  {
    id: "interrupted",
    href: "/interrupted",
    family: "condition-atlas",
    title: "interrupted",
    premise: "the process stopped before its last step.",
    focal: "broken process",
    viewerRole: "witness to interruption",
    primaryRelation: "interrupt",
    temporalLaw: "mid-sequence halt",
    mobileMode: "linear break report",
    status: "utility",
    grade: "interrogation",
  },
  {
    id: "lost",
    href: "/lost",
    family: "condition-atlas",
    title: "lost",
    premise: "nothing lies at this route. use the marked exits.",
    focal: "missing route",
    viewerRole: "navigator",
    primaryRelation: "reveal",
    temporalLaw: "route absent",
    mobileMode: "search path with known exits",
    status: "utility",
    grade: "cold-archive",
  },
  {
    id: "maintenance",
    href: "/maintenance",
    family: "condition-atlas",
    title: "maintenance",
    premise: "the house is closed for work. return when it opens.",
    focal: "care interval",
    viewerRole: "waiting caretaker",
    primaryRelation: "hold",
    temporalLaw: "scheduled interval",
    mobileMode: "vertical maintenance notice",
    status: "utility",
    grade: "cold-archive",
  },
  {
    id: "offline",
    href: "/offline",
    family: "condition-atlas",
    title: "offline",
    premise: "no outside signal. the local record remains.",
    focal: "severed connection",
    viewerRole: "isolated operator",
    primaryRelation: "occlude",
    temporalLaw: "no outside signal",
    mobileMode: "static local record",
    status: "utility",
    grade: "cold-archive",
  },
  {
    id: "pending",
    href: "/pending",
    family: "condition-atlas",
    title: "pending",
    premise: "the request was accepted. the result is not ready.",
    focal: "unfinished request",
    viewerRole: "patient observer",
    primaryRelation: "approach",
    temporalLaw: "open duration",
    mobileMode: "accepted, not complete",
    status: "utility",
    grade: "cold-archive",
  },
  {
    id: "redirecting",
    href: "/redirecting",
    family: "condition-atlas",
    title: "redirecting",
    premise: "the old route gives way to a named route.",
    focal: "changed path",
    viewerRole: "navigator",
    primaryRelation: "transpose",
    temporalLaw: "immediate transition",
    mobileMode: "explicit old and new route",
    status: "utility",
    grade: "cold-archive",
  },
  {
    id: "unauthorized",
    href: "/unauthorized",
    family: "condition-atlas",
    title: "unauthorized",
    premise: "identity is not verified.",
    focal: "unverified identity",
    viewerRole: "arriving visitor",
    primaryRelation: "interrupt",
    temporalLaw: "held threshold",
    mobileMode: "clear identity path",
    status: "utility",
    grade: "interrogation",
  },
];

export const showcaseManifests: readonly ShowcaseManifest[] = [
  {
    id: "home",
    href: "/",
    family: "frontispiece",
    title: "hyvui",
    premise: "same parts. new ties, new page.",
    focal: "four authored scenes",
    viewerRole: "entering witness",
    primaryRelation: "procession",
    temporalLaw: "enter, then compare",
    mobileMode: "vertical frontispiece",
    status: "published",
    hostBiome: "manifesto-print",
    weight: "field-notebook",
    grade: "twilight",
  },
  {
    id: "bridge",
    href: "/examples/bridge",
    family: "scene",
    title: "the carrier's bridge",
    premise: "the bridge keeps watch while the contacts move.",
    focal: "persistent contact",
    viewerRole: "operator",
    primaryRelation: "trace",
    temporalLaw: "continuous watch",
    mobileMode: "stacked watch stations",
    status: "published",
    hostBiome: "operational-apparatus",
    grafts: ["celestial-cartography:framing"],
    weight: "mission-control",
    theme: "hextech",
    grade: "interrogation",
  },
  {
    id: "keeper",
    href: "/examples/keeper",
    family: "scene",
    title: "the keeper's index",
    premise: "the book is damaged. the record must stay clear.",
    focal: "damaged letter book",
    viewerRole: "archivist",
    primaryRelation: "preserve",
    temporalLaw: "accumulated handling",
    mobileMode: "index before detail",
    status: "published",
    hostBiome: "quiet-object-gallery",
    grafts: ["deconstructed-editorial:information"],
    weight: "archive",
    grade: "cold-archive",
  },
  {
    id: "correspondence",
    href: "/examples/correspondence",
    family: "scene",
    title: "field correspondence",
    premise: "the draft says what the sender cannot yet say.",
    focal: "unfinished letter",
    viewerRole: "reader",
    primaryRelation: "reveal",
    temporalLaw: "draft and return",
    mobileMode: "linear letter with marginalia",
    status: "published",
    hostBiome: "deconstructed-editorial",
    grafts: ["manifesto-print:typography"],
    weight: "field-notebook",
    grade: "twilight",
  },
  {
    id: "watchhouse",
    href: "/examples/watchhouse",
    family: "scene",
    title: "the watchhouse",
    premise: "one light returns. the watch records each return.",
    focal: "recurring sighting",
    viewerRole: "caretaker-witness",
    primaryRelation: "echo",
    temporalLaw: "recurrence",
    mobileMode: "vertical logbook procession",
    status: "published",
    hostBiome: "ecological-elegy",
    grafts: ["machine-ecology:motion"],
    weight: "field-notebook",
    theme: "arcane",
    grade: "twilight",
  },
  {
    id: "hextech",
    href: "/showcase/hextech",
    family: "material-study",
    title: "rig iv",
    premise: "brass holds the crystal at a measured charge.",
    focal: "crystal chamber",
    viewerRole: "workshop operator",
    primaryRelation: "contain",
    temporalLaw: "calibration and release",
    mobileMode: "schematic before mechanism",
    status: "published",
    hostBiome: "operational-apparatus",
    weight: "mission-control",
    theme: "hextech",
    grade: "interrogation",
  },
  {
    id: "arcane",
    href: "/showcase/arcane",
    family: "material-study",
    title: "the manifest",
    premise: "the manifestation is read by the marks it leaves.",
    focal: "manifestation",
    viewerRole: "reverent witness",
    primaryRelation: "reveal",
    temporalLaw: "breathing manifestation",
    mobileMode: "relic before inscription",
    status: "published",
    hostBiome: "ceremonial-reliquary",
    weight: "field-notebook",
    theme: "arcane",
    grade: "twilight",
  },
  {
    id: "docs",
    href: "/docs",
    family: "field-guide",
    title: "field guide",
    premise: "a part is easier to use when its role is shown beside its props.",
    focal: "live component specimens",
    viewerRole: "author",
    primaryRelation: "annotate",
    temporalLaw: "inspect and return",
    mobileMode: "index then specimen",
    status: "utility",
    hostBiome: "deconstructed-editorial",
    weight: "archive",
    grade: "cold-archive",
  },
  {
    id: "system",
    href: "/system",
    family: "condition-atlas",
    title: "condition atlas",
    premise: "when a route fails, the page must say so.",
    focal: "state sequence",
    viewerRole: "navigator",
    primaryRelation: "procession",
    temporalLaw: "state change",
    mobileMode: "linear state index",
    status: "utility",
    hostBiome: "operational-apparatus",
    weight: "mission-control",
    grade: "interrogation",
  },
  ...conditionRoutes,
  {
    id: "system-cinematic",
    href: "/system/cinematic",
    family: "condition-atlas",
    title: "cinematic system",
    premise: "light, grade, and time are separate controls.",
    focal: "weight, theme, and grade",
    viewerRole: "system author",
    primaryRelation: "transpose",
    temporalLaw: "replayable sequence",
    mobileMode: "stacked controls before specimen",
    status: "utility",
    weight: "field-notebook",
    grade: "twilight",
  },
  {
    id: "system-ornament-patterns",
    href: "/system/ornament-patterns",
    family: "condition-atlas",
    title: "ornament patterns",
    premise: "the same mark reads differently in each register.",
    focal: "ornament grammar",
    viewerRole: "system author",
    primaryRelation: "echo",
    temporalLaw: "live retuning",
    mobileMode: "controls before pattern index",
    status: "utility",
    weight: "field-notebook",
  },
  {
    id: "lab",
    href: "/lab",
    family: "stress-observatory",
    title: "stress observatory",
    premise: "bad content finds weak layout.",
    focal: "pathological specimen",
    viewerRole: "test operator",
    primaryRelation: "interrupt",
    temporalLaw: "repeatable stress",
    mobileMode: "one fixed-width specimen at a time",
    status: "utility",
    hostBiome: "operational-apparatus",
    weight: "mission-control",
    grade: "interrogation",
  },
  {
    id: "next-biomes",
    href: "/next-lab/biomes",
    family: "research-archive",
    title: "biome proof gallery",
    premise: "one set of words. six hosts. each keeps its own rule.",
    focal: "shared content corpus",
    viewerRole: "comparative witness",
    primaryRelation: "transpose",
    temporalLaw: "held frames",
    mobileMode: "one proof frame at a time",
    status: "experimental",
  },
  {
    id: "next-biome-plan",
    href: "/next-lab/biome-plan",
    family: "research-archive",
    title: "resolved biome plan",
    premise: "name the rules, then inspect the composition.",
    focal: "resolved plan",
    viewerRole: "composition author",
    primaryRelation: "annotate",
    temporalLaw: "static inspection",
    mobileMode: "linear plan report",
    status: "experimental",
  },
  {
    id: "next-frames",
    href: "/next-lab/frames",
    family: "research-archive",
    title: "native frame sequence",
    premise: "a native link can carry a scene change.",
    focal: "held frame",
    viewerRole: "navigator",
    primaryRelation: "approach",
    temporalLaw: "discrete scenes",
    mobileMode: "one frame per viewport",
    status: "experimental",
  },
  {
    id: "next-passage",
    href: "/next-lab/passage",
    family: "research-archive",
    title: "ecological passage",
    premise: "each step changes the visible edge and field.",
    focal: "absorbing field",
    viewerRole: "traveler",
    primaryRelation: "absorb",
    temporalLaw: "accumulation",
    mobileMode: "static reading fallback",
    status: "experimental",
  },
  {
    id: "next-measured-sublime",
    href: "/next-lab/measured-sublime",
    family: "research-archive",
    title: "measured sublime",
    premise: "the relation moves the signal while the text stays put.",
    focal: "decision specimen",
    viewerRole: "investigator",
    primaryRelation: "reveal",
    temporalLaw: "finite exposure",
    mobileMode: "vertical evidence sequence",
    status: "experimental",
  },
  {
    id: "next-experiment",
    href: "/next-lab/experiment",
    family: "research-archive",
    title: "composition experiment",
    premise: "a relation may place a node without changing document flow.",
    focal: "composition graph",
    viewerRole: "composition author",
    primaryRelation: "connect",
    temporalLaw: "deterministic projection",
    mobileMode: "semantic flow with local projection",
    status: "experimental",
  },
  {
    id: "next-baseline",
    href: "/next-lab/baseline",
    family: "research-archive",
    title: "current-library baseline",
    premise: "use the current page as the control.",
    focal: "control composition",
    viewerRole: "reviewer",
    primaryRelation: "compare",
    temporalLaw: "repeatable control",
    mobileMode: "contained baseline case",
    status: "experimental",
  },
  {
    id: "next-witness",
    href: "/next-lab/witness",
    family: "research-archive",
    title: "focus and context",
    premise: "focus shows one marker. context shows three.",
    focal: "selected observation",
    viewerRole: "investigator",
    primaryRelation: "reveal",
    temporalLaw: "focus and context",
    mobileMode: "field before record",
    status: "experimental",
    hostBiome: "operational-apparatus",
    grafts: ["celestial-cartography:framing"],
    weight: "mission-control",
    grade: "interrogation",
  },
];

export function getShowcaseManifest(id: string): ShowcaseManifest | undefined {
  return showcaseManifests.find((manifest) => manifest.id === id);
}
